### ISSUE TITLE
Make CREDEBL white label (frontend)

### ISSUE THREAD

**Issue by sanjay-k1910** [credebl/studio#382]
**User Story**
As a CREDEBL user, In the white label dashboard, I can able to customize the application's branding, including the app's name, and logo.

 Tasks
 - [x] Added `.env` variables
 - [x] Updated config file with white labeling data
 - [x] Implement dynamic white labeling data on throughout the application
 - [x] Handle dynamic `.env` variables to set globally

**Comment by ankita-p17** [comment]
This is completed.
