### ISSUE TITLE
UI for the Client credentials

### ISSUE THREAD

**Issue by 16-karan** [credebl/studio#533]
- [x] Development of UI
- [x] API's integrations

**Acceptance Criteria:** 
**Creating ClientID and ClientSecret:** 

- As an organization Owner, I should be able to create clientId and clientSecret
- The client ID and client secret should be visible to the organization's owner and admin

**Deleting ClientSecret:**

- As an organization Owner or Admin, when I navigate to the client details page, there should be an option to delete the associated 
Client Secret

**Copy ClientSecret:** 

- As an organization Owner, I should be able to copy clientSecret when create clientSecret but after refresh not able to view copy button
- The copy functionality should be available immediately after the creation of the clientSecret
- After refreshing or reloading the page, the "Copy" button should no longer be visible, ensuring that the Client Secret cannot be copied again

**Masking ClientSecret after Reload:**

- As an organization Owner or Admin, after creating a new Client Secret and refreshing the page, the Client Secret should be masked

**Comment by sunilbade** [comment]
Tested on the QA environment and changes look fine as per the acceptance criteria.
