### ISSUE TITLE
feat: add support for multiple did methods in CREDEBL studio

### ISSUE THREAD

**Issue by pranalidhanavade** [credebl/studio#534]
**Acceptance Criteria:** 
As an organization Owner or Admin,
- [x] I should be able to view dropdown with all the did methods
- [x] I should be able to create a wallet using did:indy, did:key, did:web methods
- [x] After creating a wallet, the details of the created DID method should be visible in the wallet details section
- [x] If Success, I should be able to get all the details about the wallet
- [x] If Failure, I should be able to view the error message

**Comment by bhavanakarwade** [comment]
This task is completed
