### ISSUE TITLE
Implementation create schema functionality in OOB Bulk and Email Issuance

### ISSUE THREAD

**Issue by 16-karan** [credebl/studio#541]
- Add create schema functionality
- [x] In OOB Bulk Issuance
- [x] In OOB Email Issunace

**Comment by sunilbade** [comment]
Tested on the DEV environment and changes look fine



![Image](https://github.com/credebl/studio/assets/126459604/f5fd7d43-18e5-4bc3-b8c1-4fceebec4e02)



![Image](https://github.com/credebl/studio/assets/126459604/f21fed87-18bc-4937-8efd-94f0db524ef3)
