### ISSUE TITLE
Add Wallet Type information (Shared/Dedicated) in Wallet Detail page

### ISSUE THREAD

**Issue by amitayanworks** [credebl/studio#99]
- API is ready, change the UI to implement the changes
- Also check the Wrong Wallet Date in the details

**Comment by amitayanworks** [comment]
Bhavana was busy on Edit profile, so will pick the task today

**Comment by sayali-chavan96** [comment]
Tested on DEV environment and changes look fine


![Image](https://github.com/credebl/studio/assets/133863994/56c93b57-ed68-4ac9-8be9-26473cb536ff)



![Image](https://github.com/credebl/studio/assets/133863994/fdbb6a9b-13df-4321-bc80-84232dc5d33c)
